### ISSUE TITLE
.pre-commit-hooks.yaml does not exist

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffoldext-dsproject#15]
Currently, the unit tests on master fail for Mac [since .pre-commit-hooks.yaml does not exist when running pre-commit.](https://cirrus-ci.com/task/6047822871003136).
@abravalheri Do you have any idea why this happens for Mac? I am kind of lost on that one :-/

**Comment by abravalheri** [comment]
That is surprising! Specially because the logs clearly say it was created (`create    my_project/.pre-commit-config.yaml`). It looks like there is a problem with the `cwd` (it is looking for `/Users/anka/.cache/pre-commit/repo_du3uz9s/.pre-commit-hooks.yaml` but I think the root directory should not be that one)... I will try to have a proper look on this issue later today or during the weekend. It is very weird indeed...

**Comment by abravalheri** [comment]
So I ended up misusing a draft PR that I had open at PyScaffold to investigate this problem...
As I suspected, it seems that the cache is what is problematic. When I simply [removed pre-commit caching](https://github.com/pyscaffold/pyscaffold/pull/398/commits/efbf154dc02266a227857e12f3e5c46a17ab5738), the tests worked, and then when I [put it back](https://github.com/pyscaffold/pyscaffold/pull/398/commits/6399fcd07a6b9fd5ff625381a3e6f64036fc4b4e), they stopped working (probably Cirrus CI downloaded an old cache?). The other solution is to keep the cache but use a fingerprint as indicated in this [commit](https://github.com/pyscaffold/pyscaffold/pull/398/commits/b3350c0221a5908bc304ac3143f8e24af6c11d43)...

**Comment by FlorianWilhelm** [comment]
Wow, thanks! It's strange though that it only happens for MacOS. Should we better remove the cache then?

**Comment by abravalheri** [comment]
That is something I am still unsure...
In PyScaffold removing the cache increases the test times in a few minutes (2 to 3), but the alternative of using fingerprints adds complexity...

I guess we can remove it from the templates, until https://github.com/cirruslabs/cirrus-ci-docs/issues/379 is available...

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, I released a [v4.0rc2](https://pypi.org/project/PyScaffold/4.0rc2/) just in case the main repository is blocking this issue, and I also see you did the changes in the dev branch.

Hopefully, everything is right now 🤞

**Comment by FlorianWilhelm** [comment]
Thanks, @abravalheri for finding out the reasons for this strange bug!
