### ISSUE TITLE
should py.test be replace with pytest?

### ISSUE THREAD

**Issue by xg1990** [pyscaffold/pyscaffoldext-dsproject#26]
## Description of your problem

I notice this scaffold is still using `py.test`, which I think should be replaced with `pytest`

Related posts:
- https://stackoverflow.com/questions/39495429/py-test-vs-pytest-command
- https://meta.stackoverflow.com/questions/366905/rename-py-test-to-pytest?noredirect=1&lq=1

>  pytest used to be part of the py package, which provided several developer utilities, all starting with py.<TAB>, thus providing nice TAB-completion. If you install pip install pycmd you get these tools from a separate package. Once pytest became a separate package, the py.test name was retained due to avoid a naming conflict with another tool. This conflict was eventually resolved, and the pytest command was therefore introduced. In future versions of pytest, we may deprecate and later remove the py.test command to avoid perpetuating the confusion.

Happy to submit a PR if the maintainers agree this change

**Comment by FlorianWilhelm** [comment]
Hi @xg1990, thanks for bringing up this issue. I also think that we should go with the new way, i.e. `pytest`. Feel free to provide a PR, which should go into PyScaffold directly before we change the dsproject extension. Thank you.

**Comment by xg1990** [comment]
PR submitted to pyscaffold. Let's see how it goes

https://github.com/pyscaffold/pyscaffold/pull/465

**Comment by FlorianWilhelm** [comment]
Thanks, @xg1990! This should fix this issue, right?
