### ISSUE TITLE
.gitignore in configs folder

### ISSUE THREAD

**Issue by GarrisonD** [pyscaffold/pyscaffoldext-dsproject#3]
Why did you place `.gitignore` file instead of `.keep` in `configs` folder?

As far as I understand you just wanted to have `configs` folder indexed so you placed a file there but named it `.gitignore` by mistake instead of `.keep` or `.gitkeep`.

**Comment by FlorianWilhelm** [comment]
Hi, does an empty `.gitignore` hurt? My consideration was that the directory will most likely not stay empty and thus a user would have to delete a file like `.keep` or `.gitkeep`. Depending on your config files you might need some specialized `.gitignore` and thus it's already there.

**Comment by GarrisonD** [comment]
No, it doesn't hurt. It just was confusing to me.
