### ISSUE TITLE
dsproject-demo outdated

### ISSUE THREAD

**Issue by maresb** [pyscaffold/pyscaffoldext-dsproject#5]
I wanted to check the latest version of `.pre-commit-config.yaml` for dsproject-demo, but unfortunately it hasn't been updated for 13 months.

I think the ideal solution would involve triggering some CD script on every update to the main branch of PyScaffold or dsproject. That would, using tokens for someone's GitHub account, clone `dsproject-demo`, delete all files outside of `.git`, `putup`, and git add/commit/push. Once I did something similar in GitLab, but unfortunately it took some time to make sure everything was running properly. Perhaps there's some more clever way?

**Comment by FlorianWilhelm** [comment]
@maresb Smart idea! Do you have maybe a pointer to some Github Action Repo to do this?

**Comment by maresb** [comment]
Moin moin Florian, unfortunately I don't have any concrete ideas, other than what I mentioned.

**Comment by FlorianWilhelm** [comment]
Thanks @maresb. I found a Github Action that does this now automatically for each new tag on master. It's updated but there are still some problems to fix.
