### ISSUE TITLE
clarification: processed vs. preprocessed data

### ISSUE THREAD

**Issue by sgbaird** [pyscaffold/pyscaffoldext-dsproject#50]
From README:
```
├── data
│   ├── external            <- Data from third party sources.
│   ├── interim             <- Intermediate data that has been transformed.
│   ├── processed           <- The final, canonical data sets for modeling.
│   └── raw                 <- The original, immutable data dump.
```

From demo project:
![image](https://user-images.githubusercontent.com/45469701/169599442-660783db-63b4-46d0-81ed-94ea91e3c823.png)

Is this intentional?

**Comment by FlorianWilhelm** [comment]
Thanks @sgbaird, this is a bug. The directory should be named `processed` in `data` not `preprocessed`. 
As I am on a longer vacation trip right now, would you mind providing a PR? Thank you 😀 !

**Comment by sgbaird** [comment]
@FlorianWilhelm will do!

**Comment by FlorianWilhelm** [comment]
Thanks @sgbaird, this was just merged.

**Comment by FlorianWilhelm** [comment]
@sgbaird, I just pushed `v0.7.2` that includes your fix. Thanks again.
