### ISSUE TITLE
Ver 0.5a1, ${project} is not set in README.md

### ISSUE THREAD

**Issue by e13000** [pyscaffold/pyscaffoldext-dsproject#6]
I tried to setup a project using PyScaffold 4.0a3 and the dsproject extension 0.5a1. The variable ${project} is not replaced in README.md.

**Comment by FlorianWilhelm** [comment]
Thanks for posting this issue. The plugin is not yet ported to version 4.0.

**Comment by FlorianWilhelm** [comment]
@e13000, this issue is fixed on the current master
