### ISSUE TITLE
No conda package of pyscaffoldext-dsproject available 

### ISSUE THREAD

**Issue by suddenlyfleck** [pyscaffold/pyscaffoldext-dsproject#7]
Not that this is a huge problem, but pyscaffoldext-dsproject is not avaailable as a conda package.

I find this strange, since the second point in the README advocates as selling point the (internal) use of conda.

Imho, it would be nice to use conda, too, for obtaining the package. 

Best regards,
Martin

**Comment by FlorianWilhelm** [comment]
@suddenlyfleck you are absolutely right. The only reason it's not available as conda package is that right now it's not that high on our priorities. 

If you wanna help us out, this would be great! Check out https://github.com/conda-forge/pyscaffold-feedstock for inspiration :-)

**Comment by FlorianWilhelm** [comment]
Perhaps a little impertinent since you already helped so much @maresb, but if you feel the itch of converting more packages to conda, here is another one ;-)

**Comment by suddenlyfleck** [comment]
How would you rate the ration of amount of initial vs returning effort necessary to keep such a package?

In case there is any benefit (i.e. if some kind of returning effort is required) I can offer to help with the repeating task. 

I'd appreciate help with the initial package building process, though. Never done something like this before and time is highly limited for me right now.

Let me know what you think :)

**Comment by maresb** [comment]
I just went through the initial process. It takes quite a bit of patience because conda is so slow. It takes a few minutes each time to build, and if you have to tweak the config over and over, the time can really add up, especially if you're not good at multitasking. Once it's up and running though, it seems like minimal effort.

**Comment by suddenlyfleck** [comment]
I started using `conda` seriously since december (new position) to see what the fuss is about.

I agree, the slowness of `conda` is next to unbearable. If this does not change somewhat soonish (a year or two at max) I will be back with pip and not looking back until I hear that conda is fast as fuck ...

**Comment by maresb** [comment]
Fast as fuck conda exists, and is called [mamba](https://github.com/mamba-org/mamba). It's almost as fast as pip but with conda's do-anything awesomeness.

Unfortunately the conda packaging process still uses conda instead of mamba. I'm annoyed now because I'm no longer used to waiting!

**Comment by suddenlyfleck** [comment]
aaand my life has possible become incrementally better again. Thanks @maresb !
